// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_codegen.cpp:451

#ifndef _TAO_IDL_ECHOS_5KS1VZ_H_
#define _TAO_IDL_ECHOS_5KS1VZ_H_

#include /**/ "ace/pre.h"

#include "EchoC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:145

#if !defined (_ECHO__SARG_TRAITS_)
#define _ECHO__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Echo>
    : public
        Object_SArg_Traits_T<
            ::Echo_ptr,
            ::Echo_var,
            ::Echo_out,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:683

  template<>
  class SArg_Traits< ::Echo::List>
    : public
        Var_Size_SArg_Traits_T<
            ::Echo::List,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:73

class POA_Echo;
typedef POA_Echo *POA_Echo_ptr;

class  POA_Echo
  : public virtual PortableServer::ServantBase
{
protected:
  POA_Echo (void);

public:
  /// Useful for template programming.
  typedef ::Echo _stub_type;
  typedef ::Echo_ptr _stub_ptr_type;
  typedef ::Echo_var _stub_var_type;

  POA_Echo (const POA_Echo& rhs);
  virtual ~POA_Echo (void);

  virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

  virtual void _dispatch (
      TAO_ServerRequest & req,
      TAO::Portable_Server::Servant_Upcall *servant_upcall);
  
  ::Echo *_this (void);
  
  virtual const char* _interface_repository_id (void) const;

  // TAO_IDL - Generated from
  // /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

  virtual ::Echo::List * return_list (
    void) = 0;

  static void return_list_skel (
      TAO_ServerRequest &server_request,
      TAO::Portable_Server::Servant_Upcall *servant_upcall,
      TAO_ServantBase *servant);

  // TAO_IDL - Generated from
  // /home/joachima/devel/acetao/6_5_11-2_5_11/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

  virtual void shutdown (
    void) = 0;

  static void shutdown_skel (
      TAO_ServerRequest &server_request,
      TAO::Portable_Server::Servant_Upcall *servant_upcall,
      TAO_ServantBase *servant);
};

#include /**/ "ace/post.h"

#endif /* ifndef */

